del /F /Q *.aux
del /F /Q *.log
del /F /Q *.nav
del /F /Q *.out
del /F /Q *.snm
del /F /Q *.synctex.gz
del /F /Q *.toc
del /F /Q *.vrb
del /F /Q *.dvi
::del /F /Q *.pdf
del /F /Q *.ps
del /F /Q *.bak
